{
 "title": "LiteMon Full",
 "description": "View resources of a LiteMon node",
 "tags": [ "litemon" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(litemon_node_info,job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(litemon_node_info{job=~\"$job\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Load",
   "type": "gauge",
   "description": "1 minute average",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(litemon_load_avg_1m{job=~\"$job\",instance=~\"$instance\"}) / count(count(litemon_cpu_usage_per_core{job=~\"$job\",instance=~\"$instance\"}) by (core))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(litemon_cpu_usage_per_core{job=~\"$job\",instance=~\"$instance\"}) by (core))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "litemon_node_uptime{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "CPU/Memory/Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "litemon_cpu_usage_overall{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "litemon_mem_used_percentage{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "litemon_fs_usage_ratio{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{mountpoint}} @ {{instance}}"
    }
   ]
  },
  { "title": "Systemd", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Unit State",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "litemon_systemd_unit_state{job=~\"$job\",instance=~\"$instance\",state=\"active\"}",
     "legendFormat": "{{unit}}"
    }
   ]
  },
  { "title": "PSI", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "CPU Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rate(litemon_cpu_pressure_total{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rate(litemon_memory_pressure_total{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "I/O Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rate(litemon_io_pressure_total{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Net Recv",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(litemon_net_bytes_received_total{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{interface}} @ {{instance}}"
    },
    {
     "expr": "rate(litemon_net_errors_received_total{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Errors: {{interface}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "Net Sent",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(litemon_net_bytes_sent_total{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{interface}} @ {{instance}}"
    },
    {
     "expr": "rate(litemon_net_errors_sent_total{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Errors: {{interface}} @ {{instance}}"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Disk Read",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(litemon_disk_bytes_read_total{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{mountpoint}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "Disk Write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(litemon_disk_bytes_written_total{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{mountpoint}} @ {{instance}}"
    }
   ]
  }
 ]
}